{
 "title": "Alternative DNSBL Exporter Dashboard",
 "tags": [ "dnsbl" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(luzilla_rbls_ips_blacklisted,hostname)"
    }
   },
   {
    "name": "rbl",
    "label": "Blacklist",
    "query": {
     "query": "label_values(luzilla_rbls_listed,rbl)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Listings by Domain",
   "type": "stat",
   "description": "Number of blacklisted entries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hostname) (luzilla_rbls_ips_blacklisted{rbl=~\"$rbl\", hostname=~\"$domain\"})",
     "legendFormat": "{{rbl}}"
    }
   ]
  },
  {
   "title": "Listings by Blacklist",
   "type": "stat",
   "description": "Number of blacklisted entries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(rbl) (luzilla_rbls_ips_blacklisted{rbl=~\"$rbl\", hostname=~\"$domain\"})",
     "legendFormat": "{{rbl}}"
    }
   ]
  },
  { "title": "$domain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "domain" },
  {
   "title": "Domain state over time",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(hostname, ip, rbl) (luzilla_rbls_ips_blacklisted{hostname=~\"$domain\", rbl=~\"$rbl\"})",
     "legendFormat": "{{ip}} @{{rbl}}"
    }
   ]
  }
 ]
}