{
 "title": "DNSBL Exporter Dashboard",
 "description": "A small dashboard for the dnsbl-exporter",
 "tags": [
  "prometheus",
  "dnsbl",
  "blocklist",
  "dns",
  "email",
  "mail",
  "smtp"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "luzilla_rbls_targets{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RBLs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "luzilla_rbls_used{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Check Duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "luzilla_rbls_duration{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Listing by RBL",
   "type": "stat",
   "description": "Shows number of listings in each RBL. Any number outside of 0 is bad.",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(luzilla_rbls_listed{}) by(rbl)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "max(luzilla_rbls_ips_blacklisted{}) by(hostname, ip)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}