task:
  matrix:
    - name: freebsd-14
      freebsd_instance:
        image_family: freebsd-14-2
    - name: freebsd-15
      freebsd_instance:
        image_family: freebsd-15-0-snap
  provision_script:
  - pkg install -y lang/go git-lite devel/goreleaser
  script:
  - uname -a
  - goreleaser build --single-target --snapshot --clean
  - ./dist/dnsbl_exporter_freebsd_amd64_v1/dnsbl-exporter -h
