version: 2
project_name: dnsbl_exporter

before:
  hooks:
    - go mod tidy
    - go mod verify
    - helm package chart/
builds:
- id: dnsbl_exporter
  main: ./dnsbl_exporter.go
  binary: dnsbl-exporter
  ldflags: -s -w -X main.exporterVersion={{.Version}}
  goos:
  - darwin
  - freebsd
  - linux
  - windows
  env:
  - CGO_ENABLED=0
dockers_v2:
  - id: docker
    dockerfile: .docker/dnsbl-exporter/Dockerfile
    ids: [dnsbl_exporter]
    images:
      - ghcr.io/luzilla/{{.ProjectName}}
    tags:
      - "{{.Tag}}"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    extra_files:
      - rbls.ini
      - targets.ini
    platforms:
      - linux/amd64
      - linux/arm64
archives:
- files:
  - none*
release:
  extra_files:
  - glob: ./dnsbl-exporter-*.tgz
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
