---
project_name: dnsbl_exporter

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- main: ./dnsbl_exporter.go
  binary: dnsbl-exporter
  ldflags: -s -w -X main.exporterVersion={{.Version}}
  goos:
  - darwin
  - freebsd
  - linux
  - windows
  env:
  - CGO_ENABLED=0
dockers:
- image_templates:
  - 'ghcr.io/luzilla/{{.ProjectName}}:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
  extra_files:
  - rbls.ini
  - targets.ini
  goarch: amd64
- image_templates:
  - 'ghcr.io/luzilla/{{.ProjectName}}:{{ .Tag }}-arm64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64"
  extra_files:
  - rbls.ini
  - targets.ini
  goarch: arm64
docker_manifests:
- name_template: ghcr.io/luzilla/{{.ProjectName}}:{{ .Tag }}
  image_templates:
  - ghcr.io/luzilla/{{.ProjectName}}:{{ .Tag }}-amd64
  - ghcr.io/luzilla/{{.ProjectName}}:{{ .Tag }}-arm64
archives:
- files:
  - none*
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
