version: 2
project_name: dnsbl_exporter

before:
  hooks:
    - go mod tidy
    - go mod verify
builds:
- main: ./dnsbl_exporter.go
  binary: dnsbl-exporter
  ldflags: -s -w -X main.exporterVersion={{.Version}}
  goos:
  - linux
  env:
  - CGO_ENABLED=0
archives:
- files:
  - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
