---
project_name: dnsbl_exporter

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- main: ./dnsbl_exporter.go
  binary: dnsbl-exporter
  ldflags: -s -w -X main.exporterVersion={{.Version}}
  goos:
  - darwin
  - freebsd
  - linux
  - windows
  env:
  - CGO_ENABLED=0
archives:
- files:
  - none*
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
