apiVersion: v1
kind: Service
metadata:
  name: {{ include "dnsbl-exporter.fullname" . }}
  labels:
    {{- include "dnsbl-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-9211
      protocol: TCP
      name: svc-9211
  selector:
    {{- include "dnsbl-exporter.selectorLabels" . | nindent 4 }}
