version: 2.1
workflows:
  main:
    jobs:
      - build
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  build:
    docker:
      - image: goreleaser/goreleaser
    steps:
      - checkout
      - run: goreleaser check
      - run: goreleaser --snapshot --rm-dist
  release:
    docker:
      - image: goreleaser/goreleaser
    steps:
      - checkout
      - run: goreleaser release --rm-dist
