name: chart

on:
  pull_request:

concurrency:
  group: chart-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        persist-credentials: false
    - uses: yokawasa/action-setup-kube-tools@9d39563c24d4a419d1a8289c34d6da5a6171252c # v0.13.5
      with:
        setup-tools: |
          helm
    - run: helm lint --strict --quiet ./chart
    - name: default install with unbound
      run: helm template --debug ./chart
    - name: install without unbound
      run: helm template --debug --set unbound.enabled=false --set config.resolver=system ./chart
