name: chart

on:
  pull_request:

concurrency:
  group: chart-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - uses: yokawasa/action-setup-kube-tools@5778123f7b071387e9c8e522492d8f39427dc6c7 # v0.13.4
      with:
        setup-tools: |
          helm
    - run: helm lint --strict --quiet ./chart
    - name: default install with unbound
      run: helm template --debug ./chart
    - name: install without unbound
      run: helm template --debug --set unbound.enabled=false --set config.resolver=system ./chart
